name: Inline
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: Write-Host 'Hello, World'
          shell: pwsh